// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type User struct {
	ID           int64
	Name         string
	Email        pgtype.Text
	Password     pgtype.Text
	AuthorStatus pgtype.Bool
	AuthorID     pgtype.Int4
}

type UserTransaction struct {
	ID                int64
	UserWalletID      pgtype.Int4
	TransactionAmount pgtype.Text
}

type UserWallet struct {
	ID     int64
	UserID pgtype.Int4
	Amount pgtype.Text
}
