version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sqlc-practice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - my-network

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-go-server-container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
