// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Property struct {
	ID           int64            `json:"id"`
	Sizeinsqfeet pgtype.Int4      `json:"sizeinsqfeet"`
	Location     pgtype.Text      `json:"location"`
	Demand       pgtype.Text      `json:"demand"`
	Status       pgtype.Text      `json:"status"`
	UserID       pgtype.Int4      `json:"user_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID             int64            `json:"id"`
	Name           string           `json:"name"`
	Email          pgtype.Text      `json:"email"`
	Password       pgtype.Text      `json:"password"`
	ProfilePicture pgtype.Text      `json:"profile_picture"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type UserTransaction struct {
	ID                int64            `json:"id"`
	Action            string           `json:"action"`
	UserWalletID      pgtype.Int4      `json:"user_wallet_id"`
	TransactionAmount pgtype.Float8    `json:"transaction_amount"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type UserWallet struct {
	ID        int64            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	Amount    pgtype.Float8    `json:"amount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
