// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserTransaction(ctx context.Context, arg CreateUserTransactionParams) (UserTransaction, error)
	CreateUserWallet(ctx context.Context, arg CreateUserWalletParams) (UserWallet, error)
	DeleteProperty(ctx context.Context, id int64) (Property, error)
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserTransaction(ctx context.Context, id int64) error
	DeleteUserWallet(ctx context.Context, id int64) error
	GetPropertyByID(ctx context.Context, id int64) (GetPropertyByIDRow, error)
	GetPropertyByUserID(ctx context.Context, userID pgtype.Int4) ([]GetPropertyByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserWallet(ctx context.Context, userID pgtype.Int4) (GetUserWalletRow, error)
	GetUserWalletByID(ctx context.Context, id int64) (GetUserWalletByIDRow, error)
	GetUserWalletTransactions(ctx context.Context, userWalletID pgtype.Int4) ([]GetUserWalletTransactionsRow, error)
	InsertProperty(ctx context.Context, arg InsertPropertyParams) (Property, error)
	ListTransactions(ctx context.Context) ([]ListTransactionsRow, error)
	ListUserWallets(ctx context.Context) ([]ListUserWalletsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateOTP(ctx context.Context, arg UpdateOTPParams) (User, error)
	UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error)
	UpdatePropertyDemand(ctx context.Context, arg UpdatePropertyDemandParams) (Property, error)
	UpdatePropertyImages(ctx context.Context, arg UpdatePropertyImagesParams) (Property, error)
	UpdatePropertyLocation(ctx context.Context, arg UpdatePropertyLocationParams) (Property, error)
	UpdatePropertySize(ctx context.Context, arg UpdatePropertySizeParams) (Property, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Property, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPicture(ctx context.Context, arg UpdateUserPictureParams) error
	UpdateUserWalletAmount(ctx context.Context, arg UpdateUserWalletAmountParams) error
}

var _ Querier = (*Queries)(nil)
